version: '2.0'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-fpm
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
        - ./:/var/www/html/
        - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
        - ./:/var/www/html/
        - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: laravel_web
      MYSQL_ROOT_PASSWORD: replace_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  #Local email server
  mail:
    user: root
    image: mailhog/mailhog
    build:
      context: .
      dockerfile: mailhog/Dockerfile
    container_name: mail
    restart: always
    tty: true
    privileged: true
    logging:
      driver: 'none'
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - maildata:/maildir
    ports:
      - ${DOCKER_MAILHOG_SMTP_PORT}:1025 # smtp server
      - ${DOCKER_MAILHOG_UI_PORT}:8025 # web ui
    networks:
      - app-network

#Volumes
volumes:
  dbdata:
    driver: local
  maildata:
    driver: local

#Docker Networks
networks:
  app-network:
    driver: bridge