version: '2.0'
services:

  #PHP Service
  wp_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: recybertech/php-mysql:8.1
    container_name: wp_app
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html/
      - ./docker/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    environment:
      SERVICE_NAME: wp_app
      SERVICE_TAGS: dev
      SRO_DB_PORT: ${SRO_DB_PORT}
    working_dir: /var/www/html/
    networks:
      - wp-network

  #Nginx Service
  wp_server:
    image: nginx:alpine
    container_name: wp_server
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wp-network

  #MySQL Service
  wp_db:
    image: mysql:5.7.32
    container_name: wp_db
    platform: linux/x86_64
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - wp_dbdata:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: wp_db
    networks:
      - wp-network

  #Local email server
  wp_mail:
    user: root
    image: mailhog/mailhog
    build:
      context: .
      dockerfile: docker/mailhog/Dockerfile
    container_name: wp_mail
    restart: always
    tty: true
    privileged: true
    logging:
      driver: 'none'
    command: [ "-storage=maildir", "-maildir-path=/maildir" ]
    volumes:
      - wp_maildata:/maildir
    ports:
      - ${DOCKER_MAILHOG_SMTP_PORT}:1025 # smtp server
      - ${DOCKER_MAILHOG_UI_PORT}:8025 # web ui
    networks:
      - wp-network

#Volumes
volumes:
  wp_dbdata:
    driver: local
  wp_maildata:
    driver: local

#Docker Networks
networks:
  wp-network:
    driver: bridge
