#!/usr/bin/expect
spawn /var/www/html/docker/drivers/openedge/src/proinst
expect "WELCOME"
send -- "\r"
expect "Company Name:"
send -- "Weingartz"
send -- "\t"
send -- "006122200"
send -- "\t"
send -- "X8DRS"
send -- "\t"
send -- "2PR2C"
send -- "\t"
send -- "NMCYM"
send -- "\x05"
expect "Data Confirmation"
send -- "Y"
expect "Continue with Installation"
send -- "I"
expect "Complete Installation"
send -- "Y"
expect "Copy Scripts?"
send -- "Y"
expect "Installing Subcomponents"
expect "Installing files"
sleep 5
expect "Tailoring"
expect "End the OpenEdge Installation"
send -- "E"
expect eof