#!/bin/sh
# /*************************************************************/
# /* Copyright (c) 1993 by Progress Software Corporation       */
# /*                                                           */
# /* All rights reserved.  No part of this program or document */
# /* may be  reproduced in  any form  or by  any means without */
# /* permission in writing from Progress Software Corporation. */
# /*************************************************************/
#
# proupdt -  script to update installed configuration
#

# set home location
home=`pwd`;export home

# setup PROTERMCAP to point at local protermcap 
PROTERMCAP=$home/protermcap;export PROTERMCAP

# setup HHPATH for Help
HHPATH=$home;export HHPATH
HOHPATH=$home;export HOHPATH

# run installation executable
./_ovrly -u 
